# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amnh_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('start_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('entry_type', models.PositiveSmallIntegerField(choices=[(0, 'Text'), (1, 'Image'), (2, 'Video')], default=0, max_length=2)),
                ('description', models.TextField(default='')),
                ('url', models.URLField(default='')),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lat', models.FloatField(default=0)),
                ('lng', models.FloatField(default=0)),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amnh_id', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, 'N/A'), (1, 'Female'), (2, 'Male')], default=0, max_length=2)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='fieldnote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Person'),
        ),
        migrations.AddField(
            model_name='fieldnote',
            name='expedition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Expedition'),
        ),
        migrations.AddField(
            model_name='fieldentry',
            name='fieldnote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.FieldNote'),
        ),
        migrations.AddField(
            model_name='fieldentry',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Location'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='members',
            field=models.ManyToManyField(to='tracker.Person'),
        ),
    ]
