# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldentry',
            name='entry_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Text'), (1, 'Image'), (2, 'Video')], default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'N/A'), (1, 'Female'), (2, 'Male')], default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
